version: '3.8'

services:
    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        image: myapp:latest
        ports:
            - "8000:8000"
        volumes:
            - ./app:/var/www/html
        depends_on:
            - db

    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: car_leads
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
scheduler:
    image: php:8.2-cli
    working_dir: /var/www
    volumes:
        - ./:/var/www
    entrypoint: >
        sh -c "while :; do php artisan schedule:run --no-interaction; sleep 60; done"
